site_name: Mid-Willamette Area Council
site_url: https://mwasquaredance.github.io/website/
copyright: "Updated: September 2025 by Layhna"

nav:
#  - Home: index.md
  - Palette: palette/index.md
  - Clubs: clubs/index.md
#  - Calendar: calendar/index.md
#  - New Dancers: council/index.md
  - Council: council/index.md

theme:
  name: material
  icon:
    logo: material/rhombus-split    # star-four-points-box for clubs
    admonition:
      info: material/rhombus-split
#  custom_dir: overrides
  
  features:
  #  - navigation.tabs         # render top-level sections in header, >1220px viewports
  #  - navigation.tabs.sticky  # tabs always remain visible
    - navigation.sections     # top-level sections rendered as groups in sidebar
    - navigation.indexes      # page title is section title
    - navigation.instant      # internal links dispatched via XHR
    - navigation.top          # back-to-top button
    - toc.integrate           # render toc as part of left nav
  
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  
  font:
    text: Inter
    code: Fira Code

extra_css:
  - assets/extra.css
  - assets/brand.css

markdown_extensions:
  - admonition  # enables call-outs
  - attr_list   # add HTML attributes and CSS classes
  - md_in_html  # allow markdown within HTML
  - def_list    # add Definition Lists
  - tables      # adds table support
  - meta
  - pymdownx.superfences      # allows nesting
  - pymdownx.details          # allows collapsible call-outs
  - pymdownx.blocks.caption   # add captions to any markdown block
  - pymdownx.tabbed:          # allows content tabs
      alternate_style: true   # avoids wrapping tab titles on small screens
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins: []
#  - social
