# Lighting the Beacon: Square Nexus

# Built for free with Material for MkDocs


# Project Information
site_name: MWA Square Dance
site_url: https://mwasquaredance.github.io/devsite/
site_author: Layhna
copyright: "Updated: September 2025 by Layhna"  # automatically added to footer


# Repository
repo_name: mwasquaredance/devsite
repo_url: https://github.com/mwasquaredance


# Page Tree
nav:
  - Home: index.md
  - Council: council/index.md
  - Clubs: clubs/index.md
  - Directory: directory/index.md
  - Pictures: drafts/index.md
  - More Info: drafts/index.md
  - Palette: drafts/index.md


# Theme Configuration
theme:
  name: material
#  custom_dir: overrides
  font:
    text: Inter
    code: Fira Code
  icon:
    logo: material/rhombus-split
    repo: material/folder-heart    
  favicon: assets/rhombus-split.svg
  features:
    - navigation.tabs         # render top-level sections in header, >1220px viewports
  #  - navigation.tabs.sticky  # tabs always remain visible
    - navigation.sections     # top-level sections rendered as groups in sidebar
    - navigation.indexes      # page title is section title
    - navigation.instant      # internal links dispatched via XHR
    - navigation.top          # back-to-top button
    - toc.integrate           # render toc as part of left nav  
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode  

# Additional Configuration
draft_docs:   # serve but exclude from build
  drafts/
extra_css:
  - assets/extra.css
  - assets/colors.css

# Extensions
markdown_extensions:
  - admonition  # enables call-outs
  - attr_list   # add HTML attributes and CSS classes
  - def_list    # add Definition Lists
  - md_in_html  # allow markdown within HTML
  - tables      # adds table support
  - pymdownx.superfences      # allows nesting
  - pymdownx.details          # allows collapsible call-outs
  - pymdownx.blocks.caption   # add captions to any markdown block
  - pymdownx.tabbed:          # allows content tabs
      alternate_style: true   # avoids wrapping tab titles on small screens
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Plugins
plugins:
  - search
  - macros
#  - social
